### PR TITLE
add  http.Request to Connection

### PR DESCRIPTION
**Pull request by notedit**

### CODE REVIEW

**Comment by kataras** [comment]
Good but, I can't approve this type of feature because websocket implementation should be not based on any net/http or any other web library, go-websocket  is cross-framework package ( it used on iris, fasthttp and some of net/http frameworks), it will break the Iris & fasthttp websockets, we should find other way to do it, the user should be optionally, select if wants to get the http.Request or fasthttp.RequestCtx

**Comment by kataras** [comment]
Good but, I can't approve this type of feature because the main websocket implementation (connection and messages) should be not based on any net/http or any other web library, go-websocket  is cross-framework package ( it used on iris, fasthttp and some of net/http frameworks), it will break the Iris & fasthttp websockets, we should find other way to do it, the user should be optionally, select if wants to get the http.Request or fasthttp.RequestCtx

**Comment by ghost** [comment]
Good but, I can't approve this type of feature because the main websocket implementation (connection and messages) should be not based on any net/http or any other web library, go-websocket  is cross-framework package ( it used on iris, fasthttp and some of net/http frameworks), it will break the Iris & fasthttp websockets, the user/dev should be optionally, select if wants to get the http.Request or fasthttp.RequestCtx.Request, we should find other way to do it, I'm waiting for suggestions or fixes on this my friend

**Comment by notedit** [comment]
ok    i will try to   maintain a  repo my self. 

in fact i do not want to surport fasthttp.

**Comment by kataras** [comment]
@cheebhodh & @notedit  kataras/go-websocket exposes *http.Request now, just call it by `req := c.Request()`

https://github.com/kataras/go-websocket/commit/550fc8b32eb13b3b4a4bfeb227ef1a896c8f8698

**Comment by ghost** [comment]
@cheebhodh & @notedit  kataras/go-websocket exposes *http.Request now, just call it by `req := c.Request()`, no need for modified repos anymore:)

Iris(v6) example: https://github.com/iris-contrib/examples/blob/master/websocket/main.go#L34

https://github.com/kataras/go-websocket/commit/550fc8b32eb13b3b4a4bfeb227ef1a896c8f8698

 Thanks for your patience.

**Pull request closed without merging**
